Host github-cincpro
  HostName github.com
  User git
  IdentityFile ~/.ssh/witco_personal
  IdentitiesOnly yes

Host github-realgeeks
  HostName github.com
  User git
  IdentityFile ~/.ssh/github-realgeeks-auth
  IdentitiesOnly yes
